// generated by stringer -type ItemRarity; DO NOT EDIT

package main

import "fmt"

const _ItemRarity_name = "ItemGrayItemWhiteItemGreenItemBlueItemPurpleItemOrangenumItemRarity"

var _ItemRarity_index = [...]uint8{0, 8, 17, 26, 34, 44, 54, 67}

func (i ItemRarity) String() string {
	if i >= ItemRarity(len(_ItemRarity_index)-1) {
		return fmt.Sprintf("ItemRarity(%d)", i)
	}
	return _ItemRarity_name[_ItemRarity_index[i]:_ItemRarity_index[i+1]]
}
