// generated by stringer -type MonsterRarity; DO NOT EDIT

package main

import "fmt"

const _MonsterRarity_name = "MonsterGrayMonsterWhiteMonsterBronzeMonsterSilverMonsterGoldMonsterPurpleMonsterPlatinumnumMonsterRarity"

var _MonsterRarity_index = [...]uint8{0, 11, 23, 36, 49, 60, 73, 88, 104}

func (i MonsterRarity) String() string {
	if i >= MonsterRarity(len(_MonsterRarity_index)-1) {
		return fmt.Sprintf("MonsterRarity(%d)", i)
	}
	return _MonsterRarity_name[_MonsterRarity_index[i]:_MonsterRarity_index[i+1]]
}
